name: Crear y subir imagen Docker
on: 
  [workflow_dispatch]

jobs:
  publish_images: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login en DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Construir imagen
        run: docker build -t sllorennte1/ejemplo1:latest .

      - name: Subir imagen a DockerHub
        run: docker push sllorennte1/ejemplo1:latest
